services:
  db:
    container_name: db
    image: postgres:14
    ports:
      - "3000:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  minio-server:
    image: minio/minio
    volumes:
        - ~/minio_data:/data
    ports:
        - "9000:9000"
    environment:
        MINIO_ACCESS_KEY: admin
        MINIO_SECRET_KEY: admin123456
    command: server /data

  fstorage:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3001:3001"


volumes:
  db_data: