"""Fixed typo in field names

Revision ID: dce60856fb03
Revises: 1c890954ad50
Create Date: 2025-03-10 09:32:20.288587

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dce60856fb03"
down_revision: Union[str, None] = "1c890954ad50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files", sa.Column("bucket_name", sa.String(length=40), nullable=False)
    )
    op.create_unique_constraint(None, "files", ["id"])
    op.drop_column("files", "backet_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files",
        sa.Column(
            "backet_name",
            sa.VARCHAR(length=40),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "files", type_="unique")
    op.drop_column("files", "bucket_name")
    # ### end Alembic commands ###
